[colors.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[colors.normal]
black = "#000000"
blue = "#5555ff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#d8d8d8"
yellow = "#ffff55"

[colors.primary]
background = "#000000"
foreground = "#d8d8d8"

[font]
size = 8.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"

[window.padding]
x = 4
y = 4
