theme = "oled_gruvbox_dark"

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = true
continue-comments = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = false
path-completion = true
auto-format = true
completion-replace = true
auto-info = false
true-color = true
undercurl = true
bufferline = "multiple"
auto-pairs = true
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = []
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = true
auto-signature-help = false
display-inlay-hints = false
goto-reference-include-declaration = true

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker_in_current_buffer_directory"
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]

[keys.normal]
C-o = ":config-open"
C-s = ":config-reload"
C-n = "completion"
C-b = "@ b%id "
A-y = ":yank-diagnostic"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.insert]
C-n = "completion"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
