#!/bin/sh

xset s off -dpms &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
flameshot &
picom --config ~/.config/picom/picom.conf --daemon &
xclip -selection clipboard &

# Kill existing polybar instances and then start a new one
if pgrep "polybar" > /dev/null; then
  pkill -x polybar    
fi
polybar bar &

# Restart dunst if it's already running
if pgrep -x "dunst" > /dev/null; then
    pkill -x dunst
fi
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Set color scheme and other bspwm settings
bg_color="#191919"  # Dark gray background
fg_color="#c4c4b5"  # Light beige foreground (text)

focused_border_color="#97e023"  # Green border when window is focused
unfocused_border_color="#615e4b" # Dark greenish beige border when unfocused

focused_window_color="#191919"   # Dark background for focused windows
unfocused_window_color="#343434" # Dark background for unfocused windows

bspc config focused_border_color $focused_border_color
bspc config unfocused_border_color $unfocused_border_color
bspc config focused_window_border_width 2  # Border width for focused windows
bspc config unfocused_window_border_width 2  # Border width for unfocused windows

bspc config window_gap 10   # Space between windows
bspc config border_width 2  # Border width for windows

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

wmname LG3D

# Window rules for specific applications
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

