cursor #e5e2de
cursor_text_color #c9c6c2

foreground            #e5e2de
background            #131311
selection_foreground  #303126
selection_background  #c7c8b7
url_color             #c6c9b0
color0   #131311
color1   #e34a72
color2   #8fd66e
color3   #dbb57b
color4   #88943b
color5   #949687
color6   #c6c9b0
color7   #abb2bf
color8   #5c6370
color9   #e05f85
color10   #a2e086
color11   #e8c897
color12   #d3d7bc
color13   #7e7b36
color14   #717f46
color15   #ffffff
